### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by liam-portswigger** [linkedin/sometime#1]
Hi 

When I run the tool, I get this error message:

java.util.regex.PatternSyntaxException: Illegal repetition
{"userId":"0779042617780206","pageviewId":"4485103761580802","sessionId":"4960931364516096","identity":null,"trackerVersion":"3.0"}({
    at java.util.regex.Pattern.error(Pattern.java:1955)
    at java.util.regex.Pattern.closure(Pattern.java:3157)
    at java.util.regex.Pattern.sequence(Pattern.java:2134)
    at java.util.regex.Pattern.expr(Pattern.java:1996)
    at java.util.regex.Pattern.compile(Pattern.java:1696)
    at java.util.regex.Pattern.<init>(Pattern.java:1351)
    at java.util.regex.Pattern.compile(Pattern.java:1028)
    at burp.BurpExtender.doPassiveScan(BurpExtender.java:117)
    at burp.w0d.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:745)

**Comment by nwalsh1995** [comment]
This happened because there is a JSON parameter with value {"userId":"0779042617780206","pageviewId":"4485103761580802","sessionId":"4960931364516096","identity":null,"trackerVersion":"3.0"} that is throwing the regex parser off because it is interpreting this string as regex (which is not valid). 

The fix is to call Pattern.quote on the parameter before trying to create the Regex. I will submit a pull request with this fix.
